# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ezN-ZLyV4MCpFaavCMqFjUSwOe2he38f
"""

# hw_work_done_G4.py

def calculate_work_done(velocities, mass):
    """
    Calculate and yield the work done at each velocity point.

    Args:
        velocities (list): List of velocities in meters per second.
        mass (float): Mass of the car in kilograms.

    Yields:
        float: Work done at each velocity point in Joules.
    """
    prev_velocity = 0
    for velocity in velocities:
        # Calculate the change in kinetic energy (delta_ke) using the formula for kinetic energy
        delta_ke = 0.5 * mass * (velocity**2 - prev_velocity**2)
        prev_velocity = velocity  # Update the previous velocity for the next iteration
        yield delta_ke  # Yield the calculated work done at each point

